# Generated by Django 5.2.8 on 2025-11-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarefa',
            options={},
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='status',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='concluida',
            field=models.BooleanField(default=False),
        ),
    ]
